backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use Yii;
use yii\web\Controller;
use common\models\Settings;
use common\models\LoginForm;
use backend\models\menu\Menus;
use backend\models\page\Pages;
use backend\models\order\Orders;
use backend\models\product\Brands;
use backend\models\parts\HtmlParts;
use backend\models\product\Products;
use backend\models\comment\Comments;
use backend\models\product\Categories;
use backend\models\comment\CommentsSearch;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index', [
            'title' => Yii::$app->name,
            'newOrders' => count(Orders::findAll(['status' => Orders::STATUS_NEW])),
            'completedOrders' => count(Orders::findAll(['status' => Orders::STATUS_COMPLETED])),
            'allOrders' => count(Orders::find()->where(['!=', 'status', Orders::STATUS_DELETED])->all()),
            'brands' => count(Brands::find()->where(['!=', 'status', Brands::STATUS_DELETED])->all()),
            'categories' => count(Categories::find()->all()),
            'products' => count(Products::find()->where(['!=', 'status', Products::STATUS_DELETED])->all()),
            'menus' => count(Menus::find()->all()),
            'pages' => count(Pages::find()->all()),
            'blocks' => count(HtmlParts::find()->all()),
        ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            if (Yii::$app->user->can('accessDashboard')) {
                return $this->goBack();
            } else {
                Yii::$app->user->logout();
                $model->addError('password', 'Incorrect username or password.');
            }
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Ajax Set Session SidebarCollapse.
     */
    public function actionSessionSidebar()
    {
        $session = Yii::$app->session;
        $session['sidebar'] = $session['sidebar'] ? false : true;
    }

    /**
     * Displays FileManges page.
     * @return string
     */
    public function actionFiles()
    {
        return $this->render('files');
    }

    /**
     * Displays Site Setting page.
     * @return mixed
     */
    public function actionSetting()
    {
        if ($post = Yii::$app->request->post()) {
            foreach ($post as $key => $value) {
                if (($setting = Settings::findOne(['key' => $key])) !== null && !empty($value)) {
                    $setting->value = $value;
                    $setting->save();
                }
            }
            Yii::$app->session->setFlash('success', 'Settings saved.');
            return $this->refresh();
        }

        return $this->render('setting', [
            'model' => new Settings(),
            'models' => Settings::find()->all()
        ]);
    }

    /**
     * Action Create Site Setting.
     * @return mixed
     */
    public function actionSettingCreate()
    {
        $model = new Settings();
        ($model->load(Yii::$app->request->post()) && $model->save()) ?
            Yii::$app->session->setFlash('success', $model->label . ' field added.') :
            Yii::$app->session->setFlash('error', 'Field not added.');

        return $this->redirect(['setting']);
    }

    /**
     * Deletes an existing Setting model.
     * @param integer $id
     * @return mixed
     */
    public function actionSettingDelete($id)
    {
        Settings::findOne($id)->delete();
        Yii::$app->session->setFlash('warning', 'Field deleted.');

        return $this->redirect(['setting']);
    }

    /**
     * Lists all Comments models.
     * @return mixed
     */
    public function actionComments()
    {
        $searchModel = new CommentsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('comments', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Ajax SetCommentStatus.
     */
    public function actionSetCommentStatus()
    {
        if ($post = Yii::$app->request->post()) {
            if ($model = Comments::findOne($post['id'])) {
                $model->status = $post['status'];
                if ($model->save())
                    return true;
            }
        }

        return false;
    }

}

backend/views/layouts/content.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use backend\widgets\AlertGrowl;

?>
<div class="content-wrapper">
    <section class="content-header">
        <h1><?= Html::encode($this->title) ?></h1>
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
    </section>
    <section class="content">
        <?= AlertGrowl::widget() ?>
        <?= $content ?>
    </section>
</div>

<footer class="main-footer">
    <strong>&copy; Company <?= date('Y') ?>.</strong> All rights reserved.
</footer>

backend/views/layouts/header.php
<?php

/* @var $this \yii\web\View */

use yii\helpers\Url;
use yii\helpers\Html;
use rmrevin\yii\fontawesome\FA;
use common\components\languagepicker\widgets\LanguagePicker;

?>

<header class="main-header">

    <?= Html::a('<span class="logo-mini"><i class="fa fa-dashboard"></i></span><span class="logo-lg"><i class="fa fa-dashboard"></i>&nbsp;'
        . Yii::t('views', 'Dashboard') . '</span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>

    <nav class="navbar navbar-static-top" role="navigation">

        <?= Html::button('<span class="sr-only"></span>', [
            'role' => 'button',
            'class' => 'sidebar-toggle',
            'data-toggle' => 'offcanvas',
            'onclick' => '$.ajax({type : "GET", url : "' . Url::to(['/site/session-sidebar']) . '"}); return false;',
        ]) ?>

        <?php if (Yii::$app->params['multiLanguages']) { ?>
            <div class="header-language-picker">
                <?= LanguagePicker::widget([
                    'skin' => LanguagePicker::SKIN_DROPDOWN,
                    'size' => LanguagePicker::SIZE_LARGE,
                    'iconOnly' => true
                ]) ?>
            </div>
        <?php } ?>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <?php if (!Yii::$app->user->isGuest) { ?>
                    <li class="dropdown user user-menu">
                        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-user"></i>
                            <span class="hidden-xs"><?= Yii::$app->user->identity['username'] ?></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><?= Html::a(FA::i(FA::_ADDRESS_CARD) . Yii::t('views', 'Profile'),
                                    ['/admin/user/profile']) ?></li>
                            <li><?= Html::a(FA::i(FA::_EXCHANGE) . Yii::t('views', 'Change password'),
                                    ['/admin/user/change-password']) ?></li>
                            <li><?= Html::a(FA::i(FA::_SIGN_OUT) . Yii::t('views', 'Sign out'),
                                    ['/site/logout'], ['data-method' => 'POST']) ?></li>
                        </ul>
                    </li>
                <?php } ?>
            </ul>
        </div>
    </nav>
</header>

backend/views/layouts/left.php
<?php

/* @var $this \yii\web\View */

use backend\models\menu\Menus;
use backend\modules\admin\components\Helper;
use backend\extensions\adminlte\widgets\Menu;

?>

<aside class="main-sidebar">
    <section class="sidebar">

        <?= empty($menuItems = Menus::getAdminMenu()) ?
            Yii::t('views', '<pre class="bg-warning">Menu not found.<br>key => "{key}"</pre>', ['key' => 'admin_menu']) :
            Menu::widget([
                'options' => ['class' => 'sidebar-menu'],
                'items' => Helper::filter($menuItems),
            ]); ?>

    </section>
</aside>

backend/views/layouts/login.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

?>

<?= $content ?>

backend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use backend\assets\AppAsset;
use backend\extensions\adminlte\components\AdminLteHelper;

AppAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>

<?php if (Yii::$app->controller->action->id === 'login') { ?>

    <body class="login-page">
    <?php $this->beginBody() ?>

    <?= $this->render('login.php', ['content' => $content]) ?>

    <?php $this->endBody() ?>
    </body>

<?php } else { ?>

    <?php $sidebar = Yii::$app->session['sidebar'] ? ' sidebar-collapse' : ''; ?>
    <body class="<?= AdminLteHelper::skinClass() . $sidebar ?> sidebar-mini">
    <?php $this->beginBody() ?>
    <div class="wrapper">

        <?= $this->render('header.php') ?>
        <?= $this->render('left.php') ?>
        <?= $this->render('content.php', ['content' => $content]) ?>

    </div>
    <div id="overlay"></div>
    <?php $this->endBody() ?>
    </body>

<?php } ?>

</html>
<?php $this->endPage() ?>