backend/controllers/PostController.php
<?php

namespace backend\controllers;

use backend\models\product\Products;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use backend\models\post\Posts;
use backend\models\post\PostsSearch;
use backend\models\post\ProductToPost;
use backend\models\post\PostCategories;
use backend\models\post\PostCategoriesSearch;
use backend\models\product\search\ProductsSearch;

/**
 * PostController implements the CRUD actions for PostCategories model.
 */
class PostController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all PostCategories models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PostCategoriesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single PostCategories model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $searchModel = new PostsSearch(['category_id' => $id]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('view', [
            'model' => $this->findModel($id),
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new PostCategories model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new PostCategories();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing PostCategories model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing PostCategories model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the PostCategories model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return PostCategories the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = PostCategories::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /* ********** Posts Model ********** */

    /**
     * Displays a single Posts model.
     * @param integer $id
     * @return mixed
     */
    public function actionViewItem($id)
    {
        $model = $this->findModelItem($id);
        $products = new ActiveDataProvider([
            'query' => Products::find()->where([
                'id' => ArrayHelper::getColumn($model->productToPosts, 'product_id')
            ]),
            'sort' => [
                'defaultOrder' => ['id' => SORT_DESC]
            ]
        ]);

        $searchModel = new ProductsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('item/view', [
            'model' => $model,
            'products' => $products,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Posts model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @param integer $category_id
     * @return mixed
     */
    public function actionCreateItem($category_id)
    {
        $this->findModel($category_id);
        $model = new Posts(['category_id' => $category_id]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view-item', 'id' => $model->id]);
        } else {
            return $this->render('item/create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Posts model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdateItem($id)
    {
        $model = $this->findModelItem($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view-item', 'id' => $model->id]);
        } else {
            return $this->render('item/update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Posts model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDeleteItem($id)
    {
        $model = $this->findModelItem($id);
        $categoryId = $model->category_id;
        $model->delete();

        return $this->redirect(['view', 'id' => $categoryId]);

    }

    /**
     * Delete or Update an existing Posts model.
     * The browser will be redirected to the 'index' page.
     * @param integer $category_id
     * @return mixed
     */
    public function actionApplyItems($category_id)
    {
        if ($post = Yii::$app->request->post()) {
            if (isset($post['selection'])) {

                $condition = ['id' => array_map(function ($value) {
                    return (int)$value;
                }, $post['selection'])];

                switch ($post['action']) {
                    case 'deactivate':
                        Posts::updateAll(['status' => Posts::STATUS_INACTIVE], $condition);
                        Yii::$app->session->setFlash('warning', Yii::t('yii', 'Selected items <b>DEACTIVATED</b>.'));
                        break;
                    case 'activate':
                        Posts::updateAll(['status' => Posts::STATUS_ACTIVE], $condition);
                        Yii::$app->session->setFlash('success', Yii::t('yii', 'Selected items <b>ACTIVATED</b>.'));
                        break;
                    case 'delete':
                        Posts::deleteAll($condition);
                        Yii::$app->session->setFlash('danger', Yii::t('yii', 'Selected items <b>DELETED</b>.'));
                        break;
                }
            }
        }

        return $this->redirect(['view', 'id' => $category_id]);
    }

    /**
     * Finds the Posts model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Posts the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModelItem($id)
    {
        if (($model = Posts::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * ProductToPost
     * @param $id
     * @return \yii\web\Response
     */
    public function actionProductToPost($id)
    {
        if ($post = Yii::$app->request->post()) {
            if (isset($post['selection'])) {
                $productIds = array_map(function ($value) {
                    return (int)$value;
                }, $post['selection']);

                if (!empty($productIds)) {
                    ProductToPost::deleteAll(['post_id' => $id, 'product_id' => $productIds]);
                    foreach ($productIds as $productId) {
                        $relation = new ProductToPost([
                            'product_id' => $productId,
                            'post_id' => $id
                        ]);
                        $relation->save();
                    }
                }
            }
        }

        return $this->redirect(['view-item', 'id' => $id]);
    }

    /**
     * ProductToPostDelete
     * @param $id
     * @return \yii\web\Response
     */
    public function actionProductToPostDelete($id)
    {
        if ($post = Yii::$app->request->post()) {
            if (isset($post['selection'])) {
                $productIds = array_map(function ($value) {
                    return (int)$value;
                }, $post['selection']);

                if (!empty($productIds))
                    ProductToPost::deleteAll(['post_id' => $id, 'product_id' => $productIds]);
            }
        }

        return $this->redirect(['view-item', 'id' => $id]);
    }

    /**
     * ProductToPostDeleteAll
     * @param $id
     * @return \yii\web\Response
     */
    public function actionProductToPostDeleteAll($id)
    {
        ProductToPost::deleteAll(['post_id' => $id]);
        return $this->redirect(['view-item', 'id' => $id]);
    }
}

backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use Yii;
use yii\web\Controller;
use common\models\Settings;
use common\models\LoginForm;
use backend\models\menu\Menus;
use backend\models\page\Pages;
use backend\models\order\Orders;
use backend\models\product\Brands;
use backend\models\parts\HtmlParts;
use backend\models\product\Products;
use backend\models\comment\Comments;
use backend\models\product\Categories;
use backend\models\comment\CommentsSearch;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index', [
            'title' => Yii::$app->name,
            'newOrders' => count(Orders::findAll(['status' => Orders::STATUS_NEW])),
            'completedOrders' => count(Orders::findAll(['status' => Orders::STATUS_COMPLETED])),
            'allOrders' => count(Orders::find()->where(['!=', 'status', Orders::STATUS_DELETED])->all()),
            'brands' => count(Brands::find()->where(['!=', 'status', Brands::STATUS_DELETED])->all()),
            'categories' => count(Categories::find()->all()),
            'products' => count(Products::find()->where(['!=', 'status', Products::STATUS_DELETED])->all()),
            'menus' => count(Menus::find()->all()),
            'pages' => count(Pages::find()->all()),
            'blocks' => count(HtmlParts::find()->all()),
        ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            if (Yii::$app->user->can('accessDashboard')) {
                return $this->goBack();
            } else {
                Yii::$app->user->logout();
                $model->addError('password', 'Incorrect username or password.');
            }
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Ajax Set Session SidebarCollapse.
     */
    public function actionSessionSidebar()
    {
        $session = Yii::$app->session;
        $session['sidebar'] = $session['sidebar'] ? false : true;
    }

    /**
     * Displays FileManges page.
     * @return string
     */
    public function actionFiles()
    {
        return $this->render('files');
    }

    /**
     * Displays Site Setting page.
     * @return mixed
     */
    public function actionSetting()
    {
        if ($post = Yii::$app->request->post()) {
            foreach ($post as $key => $value) {
                if (($setting = Settings::findOne(['key' => $key])) !== null && !empty($value)) {
                    $setting->value = $value;
                    $setting->save();
                }
            }
            Yii::$app->session->setFlash('success', 'Settings saved.');
            return $this->refresh();
        }

        return $this->render('setting', [
            'model' => new Settings(),
            'models' => Settings::find()->all()
        ]);
    }

    /**
     * Action Create Site Setting.
     * @return mixed
     */
    public function actionSettingCreate()
    {
        $model = new Settings();
        ($model->load(Yii::$app->request->post()) && $model->save()) ?
            Yii::$app->session->setFlash('success', $model->label . ' field added.') :
            Yii::$app->session->setFlash('error', 'Field not added.');

        return $this->redirect(['setting']);
    }

    /**
     * Deletes an existing Setting model.
     * @param integer $id
     * @return mixed
     */
    public function actionSettingDelete($id)
    {
        Settings::findOne($id)->delete();
        Yii::$app->session->setFlash('warning', 'Field deleted.');

        return $this->redirect(['setting']);
    }

    /**
     * Lists all Comments models.
     * @return mixed
     */
    public function actionComments()
    {
        $searchModel = new CommentsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('comments', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Ajax SetCommentStatus.
     */
    public function actionSetCommentStatus()
    {
        if ($post = Yii::$app->request->post()) {
            if ($model = Comments::findOne($post['id'])) {
                $model->status = $post['status'];
                if ($model->save())
                    return true;
            }
        }

        return false;
    }

}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use backend\models\sliders\Sliders;
use Yii;
use yii\web\Controller;
use common\models\Settings;
use backend\models\post\Posts;
use backend\models\product\Brands;
use backend\models\product\Ribbons;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index', [
            'title' => Settings::getSiteNameValue(),
            'logo' => Yii::$app->request->hostInfo . Settings::getLogoValue(),
            'slider' => $slider = Sliders::findOne(['key' => 'home_slider', 'status' => Sliders::STATUS_ACTIVE]),
            'hurry' => Ribbons::findOne(['key' => 'hurry', 'status' => Ribbons::STATUS_ACTIVE]),
            'forFamily' => Ribbons::findOne(['key' => 'for_family', 'status' => Ribbons::STATUS_ACTIVE]),
            'manChoice' => Ribbons::findOne(['key' => 'man_choice', 'status' => Ribbons::STATUS_ACTIVE]),
            'womenThings' => Ribbons::findOne(['key' => 'women_things', 'status' => Ribbons::STATUS_ACTIVE]),
            'metaKeywords' => $this->getSettingValue('home_page_meta_keywords'),
            'metaDescription' => $this->getSettingValue('home_page_meta_description'),
            'footerText' => $this->getSettingValue('home_page_footer_text'),
            'posts' => Posts::find()->where(['status' => Posts::STATUS_ACTIVE])->orderBy(['id' => SORT_DESC])->limit(2)->all(),
            'brands' => Brands::findAll(['status' => Brands::STATUS_ACTIVE]),
        ]);
    }

    /**
     * Find Settings model.
     * @param string $key
     * @return string|null
     */
    protected function getSettingValue($key)
    {
        return (($model = Settings::findOne(['key' => $key])) !== null) ? $model->value : null;
    }
}

frontend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */
/* @var $statusCode integer */

$this->title = $name;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-error">

    <div class="row">
        <div class="col-sm-6">
            <h1><?= Html::encode(isset($exception->statusCode) ? $exception->statusCode : $exception->getCode()) ?></h1>
        </div>
        <div class="col-sm-6">
            <div class="alert alert-danger">
                <?= nl2br(Html::encode($message)) ?>
            </div>
        </div>
    </div>

</div>

frontend/views/site/index-old.php
<?php

use yii\helpers\Html;
use russ666\widgets\Countdown;

/* @var $this yii\web\View */
/* @var $slider \backend\models\sliders\Sliders */
/* @var $hurry \backend\models\product\Ribbons */
/* @var $forFamily \backend\models\product\Ribbons */
/* @var $manChoice \backend\models\product\Ribbons */
/* @var $womenThings \backend\models\product\Ribbons */
/* @var $metaKeywords string */
/* @var $metaDescription string */
/* @var $footerText string */
/* @var $brands \backend\models\product\Brands */
/* @var $posts \backend\models\post\Posts */
/* @var $title string */
/* @var $logo string */

$this->title = $title;

$this->params['meta_type'] = 'page';
$this->params['meta_url'] = Yii::$app->request->hostInfo;
$this->params['meta_image'] = $logo;
if ($metaKeywords !== null)
    $this->params['meta_keywords'] = $metaKeywords;
if ($metaDescription !== null)
    $this->params['meta_description'] = $metaDescription;

if ($footerText !== null)
    $this->params['footer_text'] = $footerText;

$hurryBlock = $hurry != null && isset($hurry->products[0]);
$hurryProduct = $hurryBlock ? $hurry->products[0] : null;
?>

<?php if ($slider != null && !empty($slider->sliderActiveItems)) { ?>
    <div class="banner">
        <div class="row">
            <div class="<?= $hurryBlock ? 'col-sm-9' : 'col-sm-12' ?>">
                <div id="kb" class="carousel slide" data-ride="carousel" data-interval="4000">
                    <!-- Wrapper-for-Slides -->
                    <div class="carousel-inner" role="listbox">
                        <?php $class = 'item active';
                        foreach ($slider->sliderActiveItems as $item) {
                            echo "<div class='$class'>";
                            echo (empty($item->link) || ($item->link == '#')) ?
                                Html::img($item->image, ['alt' => strip_tags($item->title), 'class' => 'img-responsive']) :
                                Html::a(Html::img($item->image, ['alt' => strip_tags($item->title), 'class' => 'img-responsive']), [$item->link]);
                            echo "</div>";
                            $class = 'item';
                        } ?>
                    </div>
                    <!-- Left-Button -->
                    <button class="left carousel-control kb_control_left" href="#kb" role="button"
                            data-slide="prev">
                        <span class="fa fa-angle-left kb_icons" aria-hidden="true"></span>
                    </button>
                    <!-- Right-Button -->
                    <button class="right carousel-control kb_control_right" href="#kb" role="button"
                            data-slide="next">
                        <span class="fa fa-angle-right kb_icons" aria-hidden="true"></span>
                    </button>
                </div>
            </div>
            <?php if ($hurryBlock && $hurryProduct) { ?>
                <div class="col-sm-3">
                    <div class="hurry-block">
                        <div>
                            <?= Html::a(Html::img($hurryProduct->getDefaultImageUrl(), ['alt' => 'product'])
                                . '<br><span>' . $hurryProduct->name . '</span>',
                                ['product/view', 'slug' => $hurryProduct->slug]) ?>
                        </div>
                        <ul class="price">
                            <li>
                                <del><?= $hurryProduct->getOldPriceAsCurrency() ?></del>
                            </li>
                            <li><?= $hurryProduct->getPriceAsCurrency() ?></li>
                        </ul>
                        <?php if ($hurryProduct->timer_end && $hurryProduct->timer_start && ($hurryProduct->timer_start < time()) && ($hurryProduct->timer_end > $hurryProduct->timer_start)) {
                            echo '<div class="hurry-timer"><span class="icon"><i class="fa fa-clock-o"></i></span>'
                                . Countdown::widget([
                                    'datetime' => date('Y-m-d H:i:s', $hurryProduct->timer_end),
                                    'format' => '<span><b>%-D</b><small>'
                                        . Yii::t('mp_app', ' дней')
                                        . '</small></span><span><b>| %H</b><small>'
                                        . Yii::t('mp_app', ' часов')
                                        . '</small></span><span><b>: %M</b><small>'
                                        . Yii::t('mp_app', ' минут')
                                        . '</small></span><span><b>: %S</b><small>'
                                        . Yii::t('mp_app', ' секунд')
                                        . '</small></span>',
                                    'options' => [
                                        'class' => 'count-down'
                                    ],
                                    'events' => [
                                        'finish' => 'function(){location.reload()}',
                                    ],
                                ]) . '<span class="count"><b>'
                                . $hurryProduct->quantity
                                . '</b><small>'
                                . Yii::t('mp_app', 'шт.')
                                . '</small></span></div><br><br>';
                        } ?>
                        <?= $hurryProduct->isAvailable() ? Html::button('<i class="fa fa-cart-plus"></i> '
                            . Yii::t('frontend', 'В корзину'),
                            ['class' => 'add-to-cart w3ls-cart', 'data-product' => $hurryProduct->id]) :
                            '<span class="product-not-available">' . Yii::t('frontend', 'Нет в наличии') . '</span>' ?>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
<?php } ?>

<div class="welcome">

    <?php if ($forFamily != null && !empty($forFamily->products)) { ?>
        <div class="row">
            <div class="col-md-12 welcome-item">
                <h3 class="title"><?= $forFamily->name ?></h3>
                <div id="owl-block-1" class="owl-carousel">
                    <?php foreach ($forFamily->products as $item) { ?>
                        <div class="item">
                            <div class="glry-w3agile-grids agileits">
                                <?= Html::a(Html::img($item->getDefaultImageUrl(), ['alt' => 'product']), ['/product/view', 'slug' => $item->slug]) ?>
                                <div class="view-caption agileits-w3layouts">
                                    <h4><?= Html::a($item->name, ['/product/view', 'slug' => $item->slug]) ?></h4>
                                    <h5><?= $item->getPriceAsCurrency() ?>
                                        <?= $item->getOldPriceAsCurrency() ? '<br><del>' . $item->getOldPriceAsCurrency() . '</del>' : '' ?></h5>

                                    <?= $item->isAvailable() ? Html::button('<i class="fa fa-cart-plus"></i> '
                                        . Yii::t('frontend', 'В корзину'),
                                        ['class' => 'add-to-cart w3ls-cart', 'data-product' => $item->id]) :
                                        '<span class="product-not-available">' . Yii::t('frontend', 'Нет в наличии') . '</span>' ?>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                </div>
                <?php $this->registerJs('jQuery("#owl-block-1").owlCarousel({
                    autoPlay: 3000,
                    stopOnHover: true,
                    items: 4,
                    itemsDesktop: [992, 3],
                    itemsDesktopSmall: [767, 2],
                    navigation: true
                });'); ?>
            </div>
        </div>
    <?php } ?>

    <?php if (!empty($posts)) { ?>
        <div class="home-page-posts">
            <div class="row">
                <?php foreach ($posts as $post) {
                    /* @var $post \backend\models\post\Posts */ ?>
                    <div class="col-sm-6">
                        <div class="item">
                            <?= Html::a(Html::img($post->image, ['alt' => 'post']), ['post/view', 'slug' => $post->slug]) ?>
                        </div>
                    </div>
                <?php } ?>
            </div>
        </div>
    <?php } ?>

    <?php if ($manChoice != null && !empty($manChoice->products)) { ?>
        <div class="row">
            <div class="col-md-12 welcome-item">
                <h3 class="title"><?= $manChoice->name ?></h3>
                <div id="owl-block-2" class="owl-carousel">
                    <?php foreach ($manChoice->products as $item) { ?>
                        <div class="item">
                            <div class="glry-w3agile-grids agileits">
                                <?= Html::a(Html::img($item->getDefaultImageUrl(), ['alt' => 'product']), ['/product/view', 'slug' => $item->slug]) ?>
                                <div class="view-caption agileits-w3layouts">
                                    <h4><?= Html::a($item->name, ['/product/view', 'slug' => $item->slug]) ?></h4>
                                    <h5><?= $item->getPriceAsCurrency() ?>
                                        <?= $item->getOldPriceAsCurrency() ? '<br><del>' . $item->getOldPriceAsCurrency() . '</del>' : '' ?></h5>

                                    <?= $item->isAvailable() ? Html::button('<i class="fa fa-cart-plus"></i> '
                                        . Yii::t('frontend', 'В корзину'),
                                        ['class' => 'add-to-cart w3ls-cart', 'data-product' => $item->id]) :
                                        '<span class="product-not-available">' . Yii::t('frontend', 'Нет в наличии') . '</span>' ?>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                </div>
                <?php $this->registerJs('jQuery("#owl-block-2").owlCarousel({
                    autoPlay: 3000,
                    stopOnHover: true,
                    items: 4,
                    itemsDesktop: [992, 3],
                    itemsDesktopSmall: [767, 2],
                    navigation: true
                });'); ?>
            </div>
        </div>
    <?php } ?>

    <?php if ($womenThings != null && !empty($womenThings->products)) { ?>
        <div class="row">
            <div class="col-md-12 welcome-item">
                <h3 class="title"><?= $womenThings->name ?></h3>
                <div id="owl-block-3" class="owl-carousel">
                    <?php foreach ($womenThings->products as $item) { ?>
                        <div class="item">
                            <div class="glry-w3agile-grids agileits">
                                <?= Html::a(Html::img($item->getDefaultImageUrl(), ['alt' => 'product']), ['/product/view', 'slug' => $item->slug]) ?>
                                <div class="view-caption agileits-w3layouts">
                                    <h4><?= Html::a($item->name, ['/product/view', 'slug' => $item->slug]) ?></h4>
                                    <h5><?= $item->getPriceAsCurrency() ?>
                                        <?= $item->getOldPriceAsCurrency() ? '<br><del>' . $item->getOldPriceAsCurrency() . '</del>' : '' ?></h5>

                                    <?= $item->isAvailable() ? Html::button('<i class="fa fa-cart-plus"></i> '
                                        . Yii::t('frontend', 'В корзину'),
                                        ['class' => 'add-to-cart w3ls-cart', 'data-product' => $item->id]) :
                                        '<span class="product-not-available">' . Yii::t('frontend', 'Нет в наличии') . '</span>' ?>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                </div>
                <?php $this->registerJs('jQuery("#owl-block-3").owlCarousel({
                    autoPlay: 3000,
                    stopOnHover: true,
                    items: 4,
                    itemsDesktop: [992, 3],
                    itemsDesktopSmall: [767, 2],
                    navigation: true
                });'); ?>
            </div>
        </div>
    <?php } ?>

    <?php if (!empty($brands)) { ?>
        <div class="row">
            <div class="col-md-12 welcome-item">
                <div id="owl-block-4" class="owl-carousel brands">
                    <?php foreach ($brands as $brand) {
                        /** @var $brand \backend\models\product\Brands */ ?>
                        <div class="item">
                            <?= Html::a(Html::img($brand->image, ['alt' => $brand->name]),
                                $brand->link, ['target' => '_blank']) ?>
                        </div>
                    <?php } ?>
                </div>
                <?php $this->registerJs('jQuery("#owl-block-4").owlCarousel({
                    autoPlay: 1500,
                    stopOnHover: true,
                    items: 6,
                    itemsDesktop: [992, 4],
                    itemsDesktopSmall: [767, 3],
                });'); ?>
            </div>
        </div>
    <?php } ?>

</div>